[tool.poetry]
name = "radiocore"
version = "1.0.0"
description = "Python based library for FM, AM and WBFM demodulation."
license = "GPL-3.0"
homepage = "https://github.com/luigifcruz/radio-core"
repository = "https://github.com/luigifcruz/radio-core"
documentation = "https://luigifcruz.github.io/radio-core/"
authors = [
    "Luigi Cruz <@luigifcruz>",
]

[tool.poetry.dependencies]
python = ">=3.7,<3.10"
numpy = "1.20.2"
scipy = "^1.7.1"

[tool.poetry.dev-dependencies]
pytest = "^6.2.5"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.pyright]
reportGeneralTypeIssues = true
