[project]
name = "radio-core"
version = "1.0.0"
description = "Python based library for FM, AM and WBFM demodulation."
authors = [
    "Luigi Cruz <@luigifcruz>",
]
license = "GPL-3.0"
homepage = "https://github.com/luigifcruz/radio-core"
repository = "https://github.com/luigifcruz/radio-core"
documentation = "https://luigifcruz.github.io/radio-core/"

[dependencies]
Numpy = "^1.12"
Scipy = "^1.3"

[build-system]
requires = [
    "setuptools >= 40.6.0",
    "wheel",
]

[tool.pyright]
reportGeneralTypeIssues = true
